### ISSUE TITLE
Feature: Force 2FA after first login

### ISSUE THREAD

**Issue by rrelmy** [kind-work/two-fa#10]
We would like to have an option to enforce 2FA for all users.
Optionally enforcing per role would be nice too.

After the first login the user should then be forced to setup 2FA for his account.

**Comment by jcohlmeyer** [comment]
Yes, this would be a great feature to add. I will look into adding this.

**Comment by jcohlmeyer** [comment]
I have added this feature in [v1.1.0](https://github.com/kind-work/two-fa/releases/tag/v1.1.0) @rrelmy!
