### ISSUE TITLE
Support for users in a database

### ISSUE THREAD

**Issue by martinolson** [kind-work/two-fa#12]
Do you have plans to support users stored in a database?

If not, do you foresee any problems with this addon working if I create the migration and run with it?

What fields would the migration need?

Thanks!

**Comment by jcohlmeyer** [comment]
Hey @martinolson good question. I may look into adding a database migration in the future.

For now the two fields you will need are:
| Column Name | Laravel Column Type | MySQL Column Type |
| -------------- | --------------------- | --------------------- |
| 2FA                  | char                            | CHAR(1)                     |
| two_fa             | string                          | VARCHAR                   |

**Comment by martinolson** [comment]
Thanks @jcohlmeyer, adding the migration was quick and simple and it worked great!

I created a branch with the migration here:
https://github.com/sumo-webworks/two-fa/tree/add-migration

This adds `Tag: twofa-migrations` to `php artisan vendor:publish` so that package users who store users in a database can publish the migration to their app and run it

Would you like me to open a pull request?

Thank you for your help!

**Comment by jcohlmeyer** [comment]
Yes, that would be great. Thanks.

**Comment by martinolson** [comment]
I see that the Codacy Static Code Analysis failed due to the Codacy configuration.

- Avoid using short method names like UpdateUsersTableAddKindWork2faColumns::up(). The configured minimum method name length is 3. The configured minimum method name length is 3.
- Avoid using static access to class '\Illuminate\Support\Facades\Schema' in method 'up'.

You may want to adjust the Codacy configuration to allow standard Laravel generated migrations to work.

Or not...

Thanks!

**Comment by jcohlmeyer** [comment]
Thanks, I have merged your updates into master and will publish a new release soon.
