### ISSUE TITLE
Improve one-time-code input

### ISSUE THREAD

**Issue by rrelmy** [kind-work/two-fa#15]
Currently 1Password for example does not automatically detect and fills the OTP code.

It could help to define [`autocomplete="one-time-code"`](https://developer.mozilla.org/en-US/docs/Web/HTML/Attributes/autocomplete)

**Comment by jcohlmeyer** [comment]
Thanks, this was working for me with 1Password in Safari, however I added the autocomplete attribute. Hopefully this makes the autocomplete of the OTP code more reliable.
