### ISSUE TITLE
SVG doesn't seem to be working?

### ISSUE THREAD

**Issue by artemverbo** [kind-work/two-fa#20]
Currently in Chrome SVG doesn't seem to be rendering (not base64 encoded src), please see screenshot attached, am I doing something wrong/missing any extensions for SVG to work?

Thank you!
![Markup 2021-12-14 at 16 24 54](https://user-images.githubusercontent.com/1530975/145927672-8ff8134e-b42b-4032-8fe6-f4bfbd9195bc.png)

**Comment by artemverbo** [comment]
Just to add some context, I got that state when I actually had PNG set in the options. Somehow it tried to embed SVG conde still inside the `img src=`, when switched to SVG in the config, it works.

**Comment by jcohlmeyer** [comment]
@artemverbo What version of the addon are you using? I can not seem to replicate the issue on my side or see how this could be happening. Have you tried updating to the latest version?

**Comment by jcohlmeyer** [comment]
@artemverbo I am closing this as I can not reproduce the issue. If you are still having the issue and you can send me some more details on your setup I will try to replicate the issue again.

Thanks,
Jonathan
