### ISSUE TITLE
Feature Request: Don't ask again on this browser

### ISSUE THREAD

**Issue by sunscreem** [kind-work/two-fa#21]
Would it be possible to only require 2FA if the user was arriving from a "new" browser?

**Comment by sunscreem** [comment]
@jcohlmeyer Just re-installed this locally and started testing. So far - PERFECT. Should be a licence purchase on it's way in the next few days once I've advised the client :) Thank you.

**Comment by jcohlmeyer** [comment]
Great to hear. Let me know if you run into any issues.
