### ISSUE TITLE
migration returns error when adding two_fa

### ISSUE THREAD

**Issue by Oleafeon** [kind-work/two-fa#24]
after i added 2fa and tried to login i get an error back `String data, right truncated: 1406 Data too long for column 'two_fa'`
the problem was that in the migration there was not a length added to two_fa after adding that it worked
![image](https://user-images.githubusercontent.com/20043831/159510208-9764790e-64b6-4712-9c8e-1e1c69d2a3cb.png)

**Comment by jcohlmeyer** [comment]
Thanks for sharing. I will make the change or accept a pull request from you with the fix.

**Comment by Oleafeon** [comment]
I created a pull request for you #25

**Comment by jcohlmeyer** [comment]
Thank you 🙇
