### ISSUE TITLE
issue with remember me

### ISSUE THREAD

**Issue by Oleafeon** [kind-work/two-fa#30]
When we try to enable remember me for the two fa then we get an error
![image](https://user-images.githubusercontent.com/20043831/172365582-32187387-d6b1-43f6-9060-38c34f57265a.png)
the error
![image](https://user-images.githubusercontent.com/20043831/172365665-02394430-df83-4b32-b40c-7584b1788eae.png)

**Comment by jcohlmeyer** [comment]
Interesting. That should be a built-in method from Statamic. 

What version of Statamic are you using? 

Are your users in a database?

**Comment by Oleafeon** [comment]
yes my users are in a database and i am using 3.2.39

**Comment by jcohlmeyer** [comment]
Thanks for letting me know. I don't personally store my users in a DB. I will take a look into providing a solution soon for this soon.

**Comment by jcohlmeyer** [comment]
Fixed with https://github.com/kind-work/two-fa/commit/00df9d49bc016b09409067f3862bc496e1c3a5c9

**Comment by jcohlmeyer** [comment]
@Oleafeon, sorry for the delay with this fix. There is now a fix for this issue with [v2.0.0-beta.1](https://github.com/kind-work/two-fa/releases/tag/v2.0.0-beta.1); if you could test this and get back to me if it works or if you have any issues, that would be great.

Thanks,
Jonathan

**Comment by Oleafeon** [comment]
@jcohlmeyer sorry for the late response i did not heve time to test this i am facing a couple problems 
1. it looks like there is a wrong date field
![image](https://user-images.githubusercontent.com/20043831/176643974-ac102531-b6d1-41f9-9c04-d64987dab30d.png)
2. when i tried to migrate i said i needed to remove some columns and then i lost all 2fa codes on the website so thats not good
there are a few breaking changes

**Comment by jcohlmeyer** [comment]
Sorry, I have come to the conclusion that I am unable to support this addon, it should continue to work but if you need support I suggest checking out: https://statamic.com/addons/mity-digital/two-factor
