### ISSUE TITLE
Migration issue with SQLite and PostgreSQL databases

### ISSUE THREAD

**Issue by henrikawl** [kind-work/two-fa#31]
There seems a migration issue with SQLite and PostgreSQL databases, which seems connected to `2FA` column.
SQLite and PostgreSQL databases have restrictions starting column names with digits which I guess leads this issue.
This is the error I get when running a migration which tries to update `users` table 
`SQLSTATE[HY000]: General error: 1 unrecognized token: "2FA" `

**Comment by jcohlmeyer** [comment]
Thanks for letting me know. I don't personally store my users in a DB. I will take a look into providing a solution soon for this soon.

**Comment by jcohlmeyer** [comment]
@henrikawl, sorry for the delay with this fix. There is now a fix for this issue with [v2.0.0-beta.1](https://github.com/kind-work/two-fa/releases/tag/v2.0.0-beta.1); if you could test this and get back to me if it works or if you have any issues, that would be great.

Thanks,
Jonathan
