### ISSUE TITLE
Translations do not get loaded

### ISSUE THREAD

**Issue by motion-work** [kind-work/two-fa#36]
<img width="302" alt="Screenshot 2023-01-03 at 16 15 22" src="https://user-images.githubusercontent.com/11538632/210386038-c37fd2f0-89f2-46ef-ad6b-67db19bbd237.png">
 
Just installed the package via composer and published the config but It seems that the translations won't get loaded? Did I forget something? My default Statamic language (app locale) is set to German, might this be the issue? Since there's no German translation file.

Statamic Version: `3.3.54`

**Comment by motion-work** [comment]
Solved It. App locale is set to `de`. There is currently no way to "force load" the `en` version right?

**Comment by motion-work** [comment]
just created a Pull Request: https://github.com/kind-work/two-fa/pull/37

**Comment by jcohlmeyer** [comment]
Thank you for looking into this issue and creating a translation. I will look into it and merge your pull request.

**Comment by motion-work** [comment]
Hi @jcohlmeyer cool thanks! would it be possible to merge it and release a new version by the end of this week? otherwise we have to use our fork until then, since it's for our client 😬

**Comment by jcohlmeyer** [comment]
I do not think that I can get to it today. Sorry. I plan to get to it this weekend.

**Comment by jcohlmeyer** [comment]
Hey @motion-work I have added [v2.0.0-beta.2](https://github.com/kind-work/two-fa/releases/tag/v2.0.0-beta.2) but am still not ready to push V2 because of some open issues with [#30](https://github.com/kind-work/two-fa/issues/30)

**Comment by motion-work** [comment]
that's fine for now. thank you so much for taking the time!
